// source: market_model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Currency', null, global);
goog.exportSymbol('proto.MarginCalculation', null, global);
goog.exportSymbol('proto.Market', null, global);
goog.exportSymbol('proto.MarketStatistic', null, global);
goog.exportSymbol('proto.Notice', null, global);
goog.exportSymbol('proto.StatisticPeriod', null, global);
goog.exportSymbol('proto.Symbol', null, global);
goog.exportSymbol('proto.SymbolStatistic', null, global);
goog.exportSymbol('proto.SymbolType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Market = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Market, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Market.displayName = 'proto.Market';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Symbol = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Symbol, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Symbol.displayName = 'proto.Symbol';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MarketStatistic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MarketStatistic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MarketStatistic.displayName = 'proto.MarketStatistic';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SymbolStatistic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SymbolStatistic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SymbolStatistic.displayName = 'proto.SymbolStatistic';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Currency = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Currency, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Currency.displayName = 'proto.Currency';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Notice = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Notice, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Notice.displayName = 'proto.Notice';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MarginCalculation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MarginCalculation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MarginCalculation.displayName = 'proto.MarginCalculation';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Market.prototype.toObject = function(opt_includeInstance) {
  return proto.Market.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Market} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Market.toObject = function(includeInstance, msg) {
  var f, obj = {
    tradingDate: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    sodTime: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    eodTime: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    preTradingDate: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    preSodTime: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    preEodTime: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    itayose2From: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    itayose2To: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    itayose3From: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    itayose3To: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
    itayose4From: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f,
    itayose4To: (f = jspb.Message.getField(msg, 12)) == null ? undefined : f,
    currentTime: (f = jspb.Message.getField(msg, 13)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Market}
 */
proto.Market.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Market;
  return proto.Market.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Market} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Market}
 */
proto.Market.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTradingDate(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSodTime(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEodTime(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreTradingDate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPreSodTime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPreEodTime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setItayose2From(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setItayose2To(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setItayose3From(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setItayose3To(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setItayose4From(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setItayose4To(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCurrentTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Market.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Market.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Market} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Market.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeInt64(
      13,
      f
    );
  }
};


/**
 * required string trading_date = 1;
 * @return {string}
 */
proto.Market.prototype.getTradingDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setTradingDate = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearTradingDate = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasTradingDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int64 sod_time = 2;
 * @return {number}
 */
proto.Market.prototype.getSodTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setSodTime = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearSodTime = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasSodTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int64 eod_time = 3;
 * @return {number}
 */
proto.Market.prototype.getEodTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setEodTime = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearEodTime = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasEodTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required string pre_trading_date = 4;
 * @return {string}
 */
proto.Market.prototype.getPreTradingDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setPreTradingDate = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearPreTradingDate = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasPreTradingDate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required int64 pre_sod_time = 5;
 * @return {number}
 */
proto.Market.prototype.getPreSodTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setPreSodTime = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearPreSodTime = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasPreSodTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * required int64 pre_eod_time = 6;
 * @return {number}
 */
proto.Market.prototype.getPreEodTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setPreEodTime = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearPreEodTime = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasPreEodTime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * required int64 itayose2_from = 7;
 * @return {number}
 */
proto.Market.prototype.getItayose2From = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setItayose2From = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearItayose2From = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasItayose2From = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * required int64 itayose2_to = 8;
 * @return {number}
 */
proto.Market.prototype.getItayose2To = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setItayose2To = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearItayose2To = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasItayose2To = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * required int64 itayose3_from = 9;
 * @return {number}
 */
proto.Market.prototype.getItayose3From = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setItayose3From = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearItayose3From = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasItayose3From = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * required int64 itayose3_to = 10;
 * @return {number}
 */
proto.Market.prototype.getItayose3To = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setItayose3To = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearItayose3To = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasItayose3To = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * required int64 itayose4_from = 11;
 * @return {number}
 */
proto.Market.prototype.getItayose4From = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setItayose4From = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearItayose4From = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasItayose4From = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * required int64 itayose4_to = 12;
 * @return {number}
 */
proto.Market.prototype.getItayose4To = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setItayose4To = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearItayose4To = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasItayose4To = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * required int64 current_time = 13;
 * @return {number}
 */
proto.Market.prototype.getCurrentTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.setCurrentTime = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Market} returns this
 */
proto.Market.prototype.clearCurrentTime = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Market.prototype.hasCurrentTime = function() {
  return jspb.Message.getField(this, 13) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Symbol.prototype.toObject = function(opt_includeInstance) {
  return proto.Symbol.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Symbol} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Symbol.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbolId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    symbolCode: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    type: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    baseCcy: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    counterCcy: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    pipSize: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    lotSize: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    priceDigit: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    speadDigit: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    amountDigit: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
    leverage: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f,
    displayOrder: (f = jspb.Message.getField(msg, 12)) == null ? undefined : f,
    maxOrderLot: (f = jspb.Message.getField(msg, 13)) == null ? undefined : f,
    minOrderLot: (f = jspb.Message.getField(msg, 14)) == null ? undefined : f,
    shortSwap: (f = jspb.Message.getField(msg, 15)) == null ? undefined : f,
    longSwap: (f = jspb.Message.getField(msg, 16)) == null ? undefined : f,
    incrementalTriggerLot: (f = jspb.Message.getField(msg, 17)) == null ? undefined : f,
    incrementalMarkup: (f = jspb.Message.getField(msg, 18)) == null ? undefined : f,
    ibCommission: (f = jspb.Message.getField(msg, 19)) == null ? undefined : f,
    status: (f = jspb.Message.getField(msg, 20)) == null ? undefined : f,
    quoteExpiration: (f = jspb.Message.getField(msg, 21)) == null ? undefined : f,
    tradingType: (f = jspb.Message.getField(msg, 22)) == null ? undefined : f,
    exchangeFlg: (f = jspb.Message.getField(msg, 23)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Symbol}
 */
proto.Symbol.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Symbol;
  return proto.Symbol.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Symbol} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Symbol}
 */
proto.Symbol.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSymbolId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbolCode(value);
      break;
    case 3:
      var value = /** @type {!proto.SymbolType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBaseCcy(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCounterCcy(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPipSize(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLotSize(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPriceDigit(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpeadDigit(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAmountDigit(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLeverage(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDisplayOrder(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaxOrderLot(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinOrderLot(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setShortSwap(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setLongSwap(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setIncrementalTriggerLot(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setIncrementalMarkup(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setIbCommission(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuoteExpiration(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTradingType(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setExchangeFlg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Symbol.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Symbol.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Symbol} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Symbol.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {!proto.SymbolType} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeString(
      13,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeString(
      14,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeString(
      15,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeString(
      16,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeString(
      17,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 18));
  if (f != null) {
    writer.writeString(
      18,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 19));
  if (f != null) {
    writer.writeString(
      19,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 20));
  if (f != null) {
    writer.writeInt32(
      20,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 21));
  if (f != null) {
    writer.writeInt32(
      21,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 22));
  if (f != null) {
    writer.writeInt32(
      22,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 23));
  if (f != null) {
    writer.writeInt32(
      23,
      f
    );
  }
};


/**
 * required int32 symbol_id = 1;
 * @return {number}
 */
proto.Symbol.prototype.getSymbolId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setSymbolId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearSymbolId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasSymbolId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string symbol_code = 2;
 * @return {string}
 */
proto.Symbol.prototype.getSymbolCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setSymbolCode = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearSymbolCode = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasSymbolCode = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required SymbolType type = 3;
 * @return {!proto.SymbolType}
 */
proto.Symbol.prototype.getType = function() {
  return /** @type {!proto.SymbolType} */ (jspb.Message.getFieldWithDefault(this, 3, 1));
};


/**
 * @param {!proto.SymbolType} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setType = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearType = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasType = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required string base_ccy = 4;
 * @return {string}
 */
proto.Symbol.prototype.getBaseCcy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setBaseCcy = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearBaseCcy = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasBaseCcy = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required string counter_ccy = 5;
 * @return {string}
 */
proto.Symbol.prototype.getCounterCcy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setCounterCcy = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearCounterCcy = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasCounterCcy = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * required string pip_size = 6;
 * @return {string}
 */
proto.Symbol.prototype.getPipSize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setPipSize = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearPipSize = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasPipSize = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * required string lot_size = 7;
 * @return {string}
 */
proto.Symbol.prototype.getLotSize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setLotSize = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearLotSize = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasLotSize = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * required int32 price_digit = 8;
 * @return {number}
 */
proto.Symbol.prototype.getPriceDigit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setPriceDigit = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearPriceDigit = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasPriceDigit = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * required int32 spead_digit = 9;
 * @return {number}
 */
proto.Symbol.prototype.getSpeadDigit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setSpeadDigit = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearSpeadDigit = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasSpeadDigit = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * required int32 amount_digit = 10;
 * @return {number}
 */
proto.Symbol.prototype.getAmountDigit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setAmountDigit = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearAmountDigit = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasAmountDigit = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * required int32 leverage = 11;
 * @return {number}
 */
proto.Symbol.prototype.getLeverage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setLeverage = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearLeverage = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasLeverage = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * required int32 display_order = 12;
 * @return {number}
 */
proto.Symbol.prototype.getDisplayOrder = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setDisplayOrder = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearDisplayOrder = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasDisplayOrder = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string max_order_lot = 13;
 * @return {string}
 */
proto.Symbol.prototype.getMaxOrderLot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setMaxOrderLot = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearMaxOrderLot = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasMaxOrderLot = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional string min_order_lot = 14;
 * @return {string}
 */
proto.Symbol.prototype.getMinOrderLot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setMinOrderLot = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearMinOrderLot = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasMinOrderLot = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional string short_swap = 15;
 * @return {string}
 */
proto.Symbol.prototype.getShortSwap = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setShortSwap = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearShortSwap = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasShortSwap = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string long_swap = 16;
 * @return {string}
 */
proto.Symbol.prototype.getLongSwap = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setLongSwap = function(value) {
  return jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearLongSwap = function() {
  return jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasLongSwap = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string incremental_trigger_lot = 17;
 * @return {string}
 */
proto.Symbol.prototype.getIncrementalTriggerLot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setIncrementalTriggerLot = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearIncrementalTriggerLot = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasIncrementalTriggerLot = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional string incremental_markup = 18;
 * @return {string}
 */
proto.Symbol.prototype.getIncrementalMarkup = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setIncrementalMarkup = function(value) {
  return jspb.Message.setField(this, 18, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearIncrementalMarkup = function() {
  return jspb.Message.setField(this, 18, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasIncrementalMarkup = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional string ib_commission = 19;
 * @return {string}
 */
proto.Symbol.prototype.getIbCommission = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setIbCommission = function(value) {
  return jspb.Message.setField(this, 19, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearIbCommission = function() {
  return jspb.Message.setField(this, 19, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasIbCommission = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional int32 status = 20;
 * @return {number}
 */
proto.Symbol.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setStatus = function(value) {
  return jspb.Message.setField(this, 20, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearStatus = function() {
  return jspb.Message.setField(this, 20, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional int32 quote_expiration = 21;
 * @return {number}
 */
proto.Symbol.prototype.getQuoteExpiration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setQuoteExpiration = function(value) {
  return jspb.Message.setField(this, 21, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearQuoteExpiration = function() {
  return jspb.Message.setField(this, 21, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasQuoteExpiration = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional int32 trading_type = 22;
 * @return {number}
 */
proto.Symbol.prototype.getTradingType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setTradingType = function(value) {
  return jspb.Message.setField(this, 22, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearTradingType = function() {
  return jspb.Message.setField(this, 22, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasTradingType = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional int32 exchange_flg = 23;
 * @return {number}
 */
proto.Symbol.prototype.getExchangeFlg = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {number} value
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.setExchangeFlg = function(value) {
  return jspb.Message.setField(this, 23, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Symbol} returns this
 */
proto.Symbol.prototype.clearExchangeFlg = function() {
  return jspb.Message.setField(this, 23, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Symbol.prototype.hasExchangeFlg = function() {
  return jspb.Message.getField(this, 23) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MarketStatistic.prototype.toObject = function(opt_includeInstance) {
  return proto.MarketStatistic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MarketStatistic} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarketStatistic.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbolType: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    period: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    volume: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MarketStatistic}
 */
proto.MarketStatistic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MarketStatistic;
  return proto.MarketStatistic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MarketStatistic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MarketStatistic}
 */
proto.MarketStatistic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.SymbolType} */ (reader.readEnum());
      msg.setSymbolType(value);
      break;
    case 2:
      var value = /** @type {!proto.StatisticPeriod} */ (reader.readEnum());
      msg.setPeriod(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVolume(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MarketStatistic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MarketStatistic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MarketStatistic} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarketStatistic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.SymbolType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {!proto.StatisticPeriod} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * required SymbolType symbol_type = 1;
 * @return {!proto.SymbolType}
 */
proto.MarketStatistic.prototype.getSymbolType = function() {
  return /** @type {!proto.SymbolType} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/**
 * @param {!proto.SymbolType} value
 * @return {!proto.MarketStatistic} returns this
 */
proto.MarketStatistic.prototype.setSymbolType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarketStatistic} returns this
 */
proto.MarketStatistic.prototype.clearSymbolType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarketStatistic.prototype.hasSymbolType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required StatisticPeriod period = 2;
 * @return {!proto.StatisticPeriod}
 */
proto.MarketStatistic.prototype.getPeriod = function() {
  return /** @type {!proto.StatisticPeriod} */ (jspb.Message.getFieldWithDefault(this, 2, 1));
};


/**
 * @param {!proto.StatisticPeriod} value
 * @return {!proto.MarketStatistic} returns this
 */
proto.MarketStatistic.prototype.setPeriod = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarketStatistic} returns this
 */
proto.MarketStatistic.prototype.clearPeriod = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarketStatistic.prototype.hasPeriod = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string volume = 3;
 * @return {string}
 */
proto.MarketStatistic.prototype.getVolume = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MarketStatistic} returns this
 */
proto.MarketStatistic.prototype.setVolume = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarketStatistic} returns this
 */
proto.MarketStatistic.prototype.clearVolume = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarketStatistic.prototype.hasVolume = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SymbolStatistic.prototype.toObject = function(opt_includeInstance) {
  return proto.SymbolStatistic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SymbolStatistic} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SymbolStatistic.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbolCode: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    period: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    volume: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    ticks: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SymbolStatistic}
 */
proto.SymbolStatistic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SymbolStatistic;
  return proto.SymbolStatistic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SymbolStatistic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SymbolStatistic}
 */
proto.SymbolStatistic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbolCode(value);
      break;
    case 2:
      var value = /** @type {!proto.StatisticPeriod} */ (reader.readEnum());
      msg.setPeriod(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVolume(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTicks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SymbolStatistic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SymbolStatistic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SymbolStatistic} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SymbolStatistic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.StatisticPeriod} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * required string symbol_code = 1;
 * @return {string}
 */
proto.SymbolStatistic.prototype.getSymbolCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.setSymbolCode = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.clearSymbolCode = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SymbolStatistic.prototype.hasSymbolCode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required StatisticPeriod period = 2;
 * @return {!proto.StatisticPeriod}
 */
proto.SymbolStatistic.prototype.getPeriod = function() {
  return /** @type {!proto.StatisticPeriod} */ (jspb.Message.getFieldWithDefault(this, 2, 1));
};


/**
 * @param {!proto.StatisticPeriod} value
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.setPeriod = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.clearPeriod = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SymbolStatistic.prototype.hasPeriod = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string volume = 3;
 * @return {string}
 */
proto.SymbolStatistic.prototype.getVolume = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.setVolume = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.clearVolume = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SymbolStatistic.prototype.hasVolume = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string ticks = 4;
 * @return {string}
 */
proto.SymbolStatistic.prototype.getTicks = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.setTicks = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.SymbolStatistic} returns this
 */
proto.SymbolStatistic.prototype.clearTicks = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SymbolStatistic.prototype.hasTicks = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Currency.prototype.toObject = function(opt_includeInstance) {
  return proto.Currency.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Currency} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Currency.toObject = function(includeInstance, msg) {
  var f, obj = {
    ccy: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    type: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    digit: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    exchangeable: (f = jspb.Message.getBooleanField(msg, 4)) == null ? undefined : f,
    exchangeFee: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    withdrawable: (f = jspb.Message.getBooleanField(msg, 6)) == null ? undefined : f,
    transferable: (f = jspb.Message.getBooleanField(msg, 7)) == null ? undefined : f,
    interestRate: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    interestCcy: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    policyInterestRate: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Currency}
 */
proto.Currency.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Currency;
  return proto.Currency.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Currency} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Currency}
 */
proto.Currency.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCcy(value);
      break;
    case 2:
      var value = /** @type {!proto.SymbolType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDigit(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExchangeable(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setExchangeFee(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWithdrawable(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTransferable(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setInterestRate(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setInterestCcy(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicyInterestRate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Currency.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Currency.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Currency} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Currency.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.SymbolType} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBool(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeBool(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeString(
      9,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * required string ccy = 1;
 * @return {string}
 */
proto.Currency.prototype.getCcy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setCcy = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearCcy = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasCcy = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required SymbolType type = 2;
 * @return {!proto.SymbolType}
 */
proto.Currency.prototype.getType = function() {
  return /** @type {!proto.SymbolType} */ (jspb.Message.getFieldWithDefault(this, 2, 1));
};


/**
 * @param {!proto.SymbolType} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setType = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearType = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasType = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 digit = 3;
 * @return {number}
 */
proto.Currency.prototype.getDigit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setDigit = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearDigit = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasDigit = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required bool exchangeable = 4;
 * @return {boolean}
 */
proto.Currency.prototype.getExchangeable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setExchangeable = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearExchangeable = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasExchangeable = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string exchange_fee = 5;
 * @return {string}
 */
proto.Currency.prototype.getExchangeFee = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setExchangeFee = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearExchangeFee = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasExchangeFee = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool withdrawable = 6;
 * @return {boolean}
 */
proto.Currency.prototype.getWithdrawable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setWithdrawable = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearWithdrawable = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasWithdrawable = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool transferable = 7;
 * @return {boolean}
 */
proto.Currency.prototype.getTransferable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setTransferable = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearTransferable = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasTransferable = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string interest_rate = 8;
 * @return {string}
 */
proto.Currency.prototype.getInterestRate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setInterestRate = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearInterestRate = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasInterestRate = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional string interest_ccy = 9;
 * @return {string}
 */
proto.Currency.prototype.getInterestCcy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setInterestCcy = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearInterestCcy = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasInterestCcy = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string policy_interest_rate = 10;
 * @return {string}
 */
proto.Currency.prototype.getPolicyInterestRate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.setPolicyInterestRate = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Currency} returns this
 */
proto.Currency.prototype.clearPolicyInterestRate = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Currency.prototype.hasPolicyInterestRate = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Notice.prototype.toObject = function(opt_includeInstance) {
  return proto.Notice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Notice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Notice.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    title: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    content: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    publishDate: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    currency: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    rank: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    details: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    createDate: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Notice}
 */
proto.Notice.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Notice;
  return proto.Notice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Notice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Notice}
 */
proto.Notice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPublishDate(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRank(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetails(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreateDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Notice.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Notice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Notice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Notice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt64(
      8,
      f
    );
  }
};


/**
 * required int32 type = 1;
 * @return {number}
 */
proto.Notice.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string title = 2;
 * @return {string}
 */
proto.Notice.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setTitle = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearTitle = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasTitle = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string content = 3;
 * @return {string}
 */
proto.Notice.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setContent = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearContent = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasContent = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 publish_date = 4;
 * @return {number}
 */
proto.Notice.prototype.getPublishDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setPublishDate = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearPublishDate = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasPublishDate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string currency = 5;
 * @return {string}
 */
proto.Notice.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setCurrency = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearCurrency = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasCurrency = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 rank = 6;
 * @return {number}
 */
proto.Notice.prototype.getRank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setRank = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearRank = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasRank = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string details = 7;
 * @return {string}
 */
proto.Notice.prototype.getDetails = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setDetails = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearDetails = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasDetails = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int64 create_date = 8;
 * @return {number}
 */
proto.Notice.prototype.getCreateDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.setCreateDate = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Notice} returns this
 */
proto.Notice.prototype.clearCreateDate = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Notice.prototype.hasCreateDate = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MarginCalculation.prototype.toObject = function(opt_includeInstance) {
  return proto.MarginCalculation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MarginCalculation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarginCalculation.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    caseNo: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    nonBetPercentage: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    betPercentage: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    memo: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MarginCalculation}
 */
proto.MarginCalculation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MarginCalculation;
  return proto.MarginCalculation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MarginCalculation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MarginCalculation}
 */
proto.MarginCalculation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaseNo(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNonBetPercentage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBetPercentage(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MarginCalculation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MarginCalculation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MarginCalculation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MarginCalculation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * required int32 id = 1;
 * @return {number}
 */
proto.MarginCalculation.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.setId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.clearId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarginCalculation.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string case_no = 2;
 * @return {string}
 */
proto.MarginCalculation.prototype.getCaseNo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.setCaseNo = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.clearCaseNo = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarginCalculation.prototype.hasCaseNo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string non_bet_percentage = 3;
 * @return {string}
 */
proto.MarginCalculation.prototype.getNonBetPercentage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.setNonBetPercentage = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.clearNonBetPercentage = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarginCalculation.prototype.hasNonBetPercentage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required string bet_percentage = 4;
 * @return {string}
 */
proto.MarginCalculation.prototype.getBetPercentage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.setBetPercentage = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.clearBetPercentage = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarginCalculation.prototype.hasBetPercentage = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string memo = 5;
 * @return {string}
 */
proto.MarginCalculation.prototype.getMemo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.setMemo = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.MarginCalculation} returns this
 */
proto.MarginCalculation.prototype.clearMemo = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MarginCalculation.prototype.hasMemo = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.SymbolType = {
  FX: 1,
  CFD: 2,
  INDEX: 3,
  CRYPTO: 4
};

/**
 * @enum {number}
 */
proto.StatisticPeriod = {
  DATE: 1,
  MONTH: 2,
  YEAR: 3
};

goog.object.extend(exports, proto);
