// source: pricing_model.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Band', null, global);
goog.exportSymbol('proto.Chart', null, global);
goog.exportSymbol('proto.ChartType', null, global);
goog.exportSymbol('proto.Quote', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Band = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Band, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Band.displayName = 'proto.Band';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Quote = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Quote.repeatedFields_, null);
};
goog.inherits(proto.Quote, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Quote.displayName = 'proto.Quote';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Chart = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Chart, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Chart.displayName = 'proto.Chart';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Band.prototype.toObject = function(opt_includeInstance) {
  return proto.Band.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Band} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Band.toObject = function(includeInstance, msg) {
  var f, obj = {
    price: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    volume: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    tradable: (f = jspb.Message.getBooleanField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Band}
 */
proto.Band.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Band;
  return proto.Band.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Band} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Band}
 */
proto.Band.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrice(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVolume(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTradable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Band.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Band.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Band} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Band.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * required string price = 1;
 * @return {string}
 */
proto.Band.prototype.getPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Band} returns this
 */
proto.Band.prototype.setPrice = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Band} returns this
 */
proto.Band.prototype.clearPrice = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Band.prototype.hasPrice = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string volume = 2;
 * @return {string}
 */
proto.Band.prototype.getVolume = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Band} returns this
 */
proto.Band.prototype.setVolume = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Band} returns this
 */
proto.Band.prototype.clearVolume = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Band.prototype.hasVolume = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required bool tradable = 3;
 * @return {boolean}
 */
proto.Band.prototype.getTradable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Band} returns this
 */
proto.Band.prototype.setTradable = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Band} returns this
 */
proto.Band.prototype.clearTradable = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Band.prototype.hasTradable = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Quote.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Quote.prototype.toObject = function(opt_includeInstance) {
  return proto.Quote.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Quote} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Quote.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    symbolId: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    symbolCode: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    asksList: jspb.Message.toObjectList(msg.getAsksList(),
    proto.Band.toObject, includeInstance),
    bidsList: jspb.Message.toObjectList(msg.getBidsList(),
    proto.Band.toObject, includeInstance),
    low: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    high: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    open: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    scale: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    quoteTime: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
    tickPerDay: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f,
    volumePerDay: (f = jspb.Message.getField(msg, 12)) == null ? undefined : f,
    feedTime: (f = jspb.Message.getField(msg, 13)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Quote}
 */
proto.Quote.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Quote;
  return proto.Quote.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Quote} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Quote}
 */
proto.Quote.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSymbolId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbolCode(value);
      break;
    case 4:
      var value = new proto.Band;
      reader.readMessage(value,proto.Band.deserializeBinaryFromReader);
      msg.addAsks(value);
      break;
    case 5:
      var value = new proto.Band;
      reader.readMessage(value,proto.Band.deserializeBinaryFromReader);
      msg.addBids(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLow(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setHigh(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setOpen(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScale(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setQuoteTime(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTickPerDay(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setVolumePerDay(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFeedTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Quote.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Quote.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Quote} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Quote.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAsksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.Band.serializeBinaryToWriter
    );
  }
  f = message.getBidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.Band.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeString(
      12,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeInt64(
      13,
      f
    );
  }
};


/**
 * required int64 id = 1;
 * @return {number}
 */
proto.Quote.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 symbol_id = 2;
 * @return {number}
 */
proto.Quote.prototype.getSymbolId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setSymbolId = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearSymbolId = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasSymbolId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string symbol_code = 3;
 * @return {string}
 */
proto.Quote.prototype.getSymbolCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setSymbolCode = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearSymbolCode = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasSymbolCode = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Band asks = 4;
 * @return {!Array<!proto.Band>}
 */
proto.Quote.prototype.getAsksList = function() {
  return /** @type{!Array<!proto.Band>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Band, 4));
};


/**
 * @param {!Array<!proto.Band>} value
 * @return {!proto.Quote} returns this
*/
proto.Quote.prototype.setAsksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.Band=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Band}
 */
proto.Quote.prototype.addAsks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.Band, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearAsksList = function() {
  return this.setAsksList([]);
};


/**
 * repeated Band bids = 5;
 * @return {!Array<!proto.Band>}
 */
proto.Quote.prototype.getBidsList = function() {
  return /** @type{!Array<!proto.Band>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Band, 5));
};


/**
 * @param {!Array<!proto.Band>} value
 * @return {!proto.Quote} returns this
*/
proto.Quote.prototype.setBidsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.Band=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Band}
 */
proto.Quote.prototype.addBids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.Band, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearBidsList = function() {
  return this.setBidsList([]);
};


/**
 * required string low = 6;
 * @return {string}
 */
proto.Quote.prototype.getLow = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setLow = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearLow = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasLow = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * required string high = 7;
 * @return {string}
 */
proto.Quote.prototype.getHigh = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setHigh = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearHigh = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasHigh = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * required string open = 8;
 * @return {string}
 */
proto.Quote.prototype.getOpen = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setOpen = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearOpen = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasOpen = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * required int32 scale = 9;
 * @return {number}
 */
proto.Quote.prototype.getScale = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setScale = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearScale = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasScale = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * required int64 quote_time = 10;
 * @return {number}
 */
proto.Quote.prototype.getQuoteTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setQuoteTime = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearQuoteTime = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasQuoteTime = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int32 tick_per_day = 11;
 * @return {number}
 */
proto.Quote.prototype.getTickPerDay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setTickPerDay = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearTickPerDay = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasTickPerDay = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string volume_per_day = 12;
 * @return {string}
 */
proto.Quote.prototype.getVolumePerDay = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setVolumePerDay = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearVolumePerDay = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasVolumePerDay = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional int64 feed_time = 13;
 * @return {number}
 */
proto.Quote.prototype.getFeedTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.setFeedTime = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Quote} returns this
 */
proto.Quote.prototype.clearFeedTime = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Quote.prototype.hasFeedTime = function() {
  return jspb.Message.getField(this, 13) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Chart.prototype.toObject = function(opt_includeInstance) {
  return proto.Chart.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Chart} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Chart.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    symbolId: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    symbolCode: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    low: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    high: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    open: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    close: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    volume: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    chartTime: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    chartDate: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
    type: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Chart}
 */
proto.Chart.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Chart;
  return proto.Chart.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Chart} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Chart}
 */
proto.Chart.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSymbolId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbolCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLow(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHigh(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOpen(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setClose(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setVolume(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setChartTime(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setChartDate(value);
      break;
    case 11:
      var value = /** @type {!proto.ChartType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Chart.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Chart.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Chart} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Chart.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeString(
      10,
      f
    );
  }
  f = /** @type {!proto.ChartType} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeEnum(
      11,
      f
    );
  }
};


/**
 * required int64 id = 1;
 * @return {number}
 */
proto.Chart.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 symbol_id = 2;
 * @return {number}
 */
proto.Chart.prototype.getSymbolId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setSymbolId = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearSymbolId = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasSymbolId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string symbol_code = 3;
 * @return {string}
 */
proto.Chart.prototype.getSymbolCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setSymbolCode = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearSymbolCode = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasSymbolCode = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required string low = 4;
 * @return {string}
 */
proto.Chart.prototype.getLow = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setLow = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearLow = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasLow = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required string high = 5;
 * @return {string}
 */
proto.Chart.prototype.getHigh = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setHigh = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearHigh = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasHigh = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * required string open = 6;
 * @return {string}
 */
proto.Chart.prototype.getOpen = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setOpen = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearOpen = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasOpen = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * required string close = 7;
 * @return {string}
 */
proto.Chart.prototype.getClose = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setClose = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearClose = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasClose = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string volume = 8;
 * @return {string}
 */
proto.Chart.prototype.getVolume = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setVolume = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearVolume = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasVolume = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * required int64 chart_time = 9;
 * @return {number}
 */
proto.Chart.prototype.getChartTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setChartTime = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearChartTime = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasChartTime = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * required string chart_date = 10;
 * @return {string}
 */
proto.Chart.prototype.getChartDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setChartDate = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearChartDate = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasChartDate = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * required ChartType type = 11;
 * @return {!proto.ChartType}
 */
proto.Chart.prototype.getType = function() {
  return /** @type {!proto.ChartType} */ (jspb.Message.getFieldWithDefault(this, 11, 1));
};


/**
 * @param {!proto.ChartType} value
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.setType = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Chart} returns this
 */
proto.Chart.prototype.clearType = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Chart.prototype.hasType = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * @enum {number}
 */
proto.ChartType = {
  M1: 1,
  M5: 2,
  M15: 3,
  M30: 4,
  H1: 5,
  H4: 6,
  D1: 7,
  W1: 8,
  MN: 9
};

goog.object.extend(exports, proto);
